default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: lolek123xd
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: kasyno_dev
  username: postgres
  password: lolek123xd


test:
  <<: *default
  database: kasyno_test


production:
  <<: *default
  database: kasyno_production
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>

cable:
  <<: *default
  database: kasyno_cable_production
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>


queue:
  <<: *default
  database: kasyno_queue_production
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>


cache:
  <<: *default
  database: kasyno_cache_production
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>

storage:
  <<: *default
  database: kasyno_storage_production
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>


recurring:
  <<: *default
  database: kasyno_recurring_production
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>